create table if not exists public.machinery_events (
  fingerprint text primary key,
  type text not null,
  ts timestamptz not null default now(),
  source text,
  source_id text,
  company text,
  buyer text,
  seller text,
  email text,
  category text,
  brand text,
  model text,
  location text,
  stock_ref text,
  price numeric,
  currency text,
  freshness_days numeric,
  hard_specs numeric,
  used_accepted text,
  end_user boolean default false,
  contactable boolean default false,
  budget_known boolean default false,
  deadline_known boolean default false,
  commission_pct numeric,
  commission_written boolean default false,
  specs text,
  notes text,
  status text,
  priority numeric,
  confidence text,
  learning text,
  payload jsonb
);
create index if not exists machinery_events_type_ts_idx on public.machinery_events(type, ts desc);
